/* eslint-disable import/prefer-default-export */
import { createGraphiQLFetcher } from '@graphiql/toolkit';
import { API_VERSION_2, API_CONFIG, URL_VERSION } from '../config';

export function getApiConfig(
  configList,
  router,
  apiVersion,
  dialect,
  dialectVersion,
) {
  return apiVersion === API_VERSION_2
    ? configList.find(
        config =>
          config.router === router &&
          config.apiVersion === apiVersion &&
          config.dialect === dialect &&
          config.dialectVersion === dialectVersion,
      )
    : configList.find(
        config => config.router === router && config.apiVersion === apiVersion,
      );
}

export function hasRoute(
  configList,
  router,
  apiVersion,
  dialect,
  dialectVersion,
  apiType,
) {
  return Boolean(
    apiVersion === API_VERSION_2
      ? configList.find(
          config =>
            config.router === router &&
            config.apiVersion === apiVersion &&
            config.dialect === dialect &&
            config.dialectVersion === dialectVersion &&
            config.routerUrl[apiType],
        )
      : configList.find(
          config =>
            config.router === router &&
            config.apiVersion === apiVersion &&
            config.routerUrl[apiType],
        ),
  );
}

export function getPath(
  isDefault,
  router,
  apiVersion,
  dialect,
  dialectVersion,
) {
  if (isDefault) {
    return `/${router}`;
  }

  return apiVersion === API_VERSION_2
    ? `/${router}/${apiVersion}/${dialect}/${dialectVersion}`
    : `/${router}/${apiVersion}`;
}

function isEmptyValue(value) {
  return !value || value.trim() === '{}' || value.trim() === '[]';
}

export function getQueryString(query, variables, headers, apiType) {
  const urlSearchParams = new URLSearchParams();
  urlSearchParams.set('urlVersion', String(URL_VERSION));
  if (apiType) {
    urlSearchParams.set('apiType', apiType);
  }
  if (query) {
    urlSearchParams.set('query', query);
  }
  if (!isEmptyValue(variables)) {
    urlSearchParams.set('variables', variables);
  }
  if (!isEmptyValue(headers)) {
    urlSearchParams.set('headers', headers);
  }
  return `?${urlSearchParams.toString()}`;
}

/**
 * Returns true if the URL search params were produced by a legacy version of
 * getQueryString that double-encoded values with encodeURIComponent. Legacy
 * links either have no urlVersion parameter or a urlVersion below the current
 * URL_VERSION.
 *
 * @param {URLSearchParams} params - Parsed query parameters from the URL
 * @returns {Boolean} Whether the URL is considered legacy
 */
function isLegacyUrl(params) {
  return (
    !params.has('urlVersion') || Number(params.get('urlVersion')) < URL_VERSION
  );
}

/**
 * This function exists for supporting legacy double-encoded URLs
 * generated by the old getQueryString implementation. If the URL
 * is identified as legacy by isLegacyUrl, decodeURIComponent is
 * applied to remove the extra encoding layer. If decoding fails,
 * the raw value is returned unchanged as a fallback.
 *
 * @param {String|null} value - Raw string from URLSearchParams.get()
 * @param {URLSearchParams} params - Parsed query parameters from the URL
 * @returns {String|null} Decoded string, or the original value if the URL is
 *   not legacy, the value is empty, or decoding failed
 */
function tryLegacyDecode(value, params) {
  if (!isLegacyUrl(params) || !value) {
    return value;
  }
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}

export function getQueryParameterValues(location) {
  const params = new URLSearchParams(location.search);
  const QUERY_STRING_PARAMS = ['query', 'variables', 'headers', 'apiType'];
  const result = location.search
    ? QUERY_STRING_PARAMS.reduce(
        (output, paramName) => ({
          ...output,
          [paramName]: params.has(paramName)
            ? tryLegacyDecode(params.get(paramName), params)
            : null,
        }),
        {},
      )
    : {};
  return result;
}

export function addSubscriptionKey(apiUrl, key, keyParam) {
  const url = new URL(apiUrl);
  if (key && keyParam) {
    url.searchParams.set(keyParam, key);
  }
  return url;
}

export function createGraphiQLFetcherWithSubscriptionKey(
  apiUrl,
  subscriptionKey,
  subscriptionKeyParam,
) {
  return createGraphiQLFetcher({
    url: addSubscriptionKey(apiUrl, subscriptionKey, subscriptionKeyParam),
  });
}

/**
 * Returns the preferred apiType if the given config has a route for it,
 * otherwise falls back to the first apiType that does have a route.
 * This ensures config.routerUrl[apiType] is never undefined.
 *
 * @param {String[]} configList - Parsed list of API configs
 * @param {String} preferredType - The desired API_TYPE (e.g. 'prod' or 'dev')
 * @param {String} router - Router name (e.g. 'hsl', 'waltti')
 * @param {String} apiVersion - API version (e.g. 'v1' or 'v2')
 * @param {String} dialect - API dialect (e.g. 'gtfs')
 * @param {String} dialectVersion - Dialect version (e.g. 'v1')
 * @returns {String} A valid apiType for the given config
 */
export function resolveApiType(
  configList,
  preferredType,
  router,
  apiVersion,
  dialect,
  dialectVersion,
) {
  if (
    hasRoute(
      configList,
      router,
      apiVersion,
      dialect,
      dialectVersion,
      preferredType,
    )
  ) {
    return preferredType;
  }
  return Object.keys(API_CONFIG).find(type =>
    hasRoute(configList, router, apiVersion, dialect, dialectVersion, type),
  );
}
